/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) rotational_ode_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[29] = {25, 1, 0, 25, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24};
static const casadi_int casadi_s1[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s2[4] = {0, 1, 0, 0};
static const casadi_int casadi_s3[32] = {28, 1, 0, 28, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27};

/* rotational_ode_expl_vde_adj:(i0[25],i1[25],i2[3],i3[0])->(o0[28]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a7, a8, a9;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[2]? arg[2][2] : 0;
  a2=arg[0]? arg[0][11] : 0;
  a3=arg[0]? arg[0][22] : 0;
  a4=(a2*a3);
  a5=arg[0]? arg[0][14] : 0;
  a6=arg[0]? arg[0][23] : 0;
  a7=(a5*a6);
  a4=(a4+a7);
  a7=arg[0]? arg[0][17] : 0;
  a8=arg[0]? arg[0][24] : 0;
  a9=(a7*a8);
  a4=(a4+a9);
  a1=(a1-a4);
  a4=arg[0]? arg[0][1] : 0;
  a9=(a3*a4);
  a10=arg[0]? arg[0][0] : 0;
  a11=(a6*a10);
  a9=(a9-a11);
  a11=(a9*a3);
  a12=(a3*a0);
  a13=arg[0]? arg[0][3] : 0;
  a14=(a6*a13);
  a12=(a12-a14);
  a14=(a12*a6);
  a11=(a11+a14);
  a14=arg[0]? arg[0][7] : 0;
  a15=(a3*a14);
  a16=arg[0]? arg[0][6] : 0;
  a17=(a6*a16);
  a15=(a15-a17);
  a17=(a15*a8);
  a11=(a11+a17);
  a1=(a1-a11);
  a11=arg[1]? arg[1][24] : 0;
  a17=(a1*a11);
  a18=arg[0]? arg[0][8] : 0;
  a19=(a0*a18);
  a20=arg[0]? arg[0][5] : 0;
  a21=(a14*a20);
  a19=(a19-a21);
  a21=(a10*a19);
  a22=(a4*a18);
  a23=arg[0]? arg[0][2] : 0;
  a24=(a14*a23);
  a22=(a22-a24);
  a24=(a13*a22);
  a21=(a21-a24);
  a24=(a4*a20);
  a25=(a0*a23);
  a24=(a24-a25);
  a25=(a16*a24);
  a21=(a21+a25);
  a25=(a17/a21);
  a26=(a0*a25);
  a27=arg[2]? arg[2][1] : 0;
  a28=arg[0]? arg[0][10] : 0;
  a29=(a28*a3);
  a30=arg[0]? arg[0][13] : 0;
  a31=(a30*a6);
  a29=(a29+a31);
  a31=arg[0]? arg[0][16] : 0;
  a32=(a31*a8);
  a29=(a29+a32);
  a27=(a27-a29);
  a29=(a8*a10);
  a32=(a3*a23);
  a29=(a29-a32);
  a32=(a29*a3);
  a33=(a8*a13);
  a34=(a3*a20);
  a33=(a33-a34);
  a34=(a33*a6);
  a32=(a32+a34);
  a34=(a8*a16);
  a35=(a3*a18);
  a34=(a34-a35);
  a35=(a34*a8);
  a32=(a32+a35);
  a27=(a27-a32);
  a32=(a27*a11);
  a35=(a32/a21);
  a36=(a20*a35);
  a26=(a26-a36);
  a36=arg[1]? arg[1][23] : 0;
  a37=(a1*a36);
  a38=(a37/a21);
  a39=(a14*a38);
  a26=(a26-a39);
  a39=(a27*a36);
  a40=(a39/a21);
  a41=(a18*a40);
  a26=(a26+a41);
  a41=(a10*a0);
  a42=(a13*a4);
  a41=(a41-a42);
  a41=(a41/a21);
  a42=(a41*a11);
  a43=(a10*a14);
  a44=(a16*a4);
  a43=(a43-a44);
  a43=(a43/a21);
  a44=(a43*a36);
  a42=(a42-a44);
  a44=(a13*a14);
  a45=(a16*a0);
  a44=(a44-a45);
  a44=(a44/a21);
  a45=arg[1]? arg[1][22] : 0;
  a46=(a44*a45);
  a42=(a42+a46);
  a46=(a3*a42);
  a47=(a6*a46);
  a26=(a26+a47);
  a47=(a10*a18);
  a48=(a16*a23);
  a47=(a47-a48);
  a47=(a47/a21);
  a48=(a47*a36);
  a49=(a10*a20);
  a50=(a13*a23);
  a49=(a49-a50);
  a49=(a49/a21);
  a50=(a49*a11);
  a48=(a48-a50);
  a50=(a13*a18);
  a51=(a16*a20);
  a50=(a50-a51);
  a50=(a50/a21);
  a51=(a50*a45);
  a48=(a48-a51);
  a51=(a3*a48);
  a52=(a8*a51);
  a26=(a26-a52);
  a49=(a49/a21);
  a49=(a49*a32);
  a41=(a41/a21);
  a41=(a41*a17);
  a49=(a49-a41);
  a41=(a24/a21);
  a17=(a41/a21);
  a32=arg[2]? arg[2][0] : 0;
  a52=arg[0]? arg[0][9] : 0;
  a53=(a52*a3);
  a54=arg[0]? arg[0][12] : 0;
  a55=(a54*a6);
  a53=(a53+a55);
  a55=arg[0]? arg[0][15] : 0;
  a56=(a55*a8);
  a53=(a53+a56);
  a32=(a32-a53);
  a53=(a6*a23);
  a56=(a8*a4);
  a53=(a53-a56);
  a56=(a53*a3);
  a57=(a6*a20);
  a58=(a8*a0);
  a57=(a57-a58);
  a58=(a57*a6);
  a56=(a56+a58);
  a58=(a6*a18);
  a59=(a8*a14);
  a58=(a58-a59);
  a59=(a58*a8);
  a56=(a56+a59);
  a32=(a32-a56);
  a56=(a32*a11);
  a17=(a17*a56);
  a49=(a49-a17);
  a43=(a43/a21);
  a43=(a43*a37);
  a49=(a49+a43);
  a43=(a22/a21);
  a37=(a43/a21);
  a17=(a32*a36);
  a37=(a37*a17);
  a49=(a49+a37);
  a47=(a47/a21);
  a47=(a47*a39);
  a49=(a49-a47);
  a44=(a44/a21);
  a1=(a1*a45);
  a44=(a44*a1);
  a49=(a49-a44);
  a50=(a50/a21);
  a27=(a27*a45);
  a50=(a50*a27);
  a49=(a49+a50);
  a50=(a19/a21);
  a44=(a50/a21);
  a32=(a32*a45);
  a44=(a44*a32);
  a49=(a49-a44);
  a19=(a19*a49);
  a26=(a26+a19);
  if (res[0]!=0) res[0][0]=a26;
  a56=(a56/a21);
  a26=(a20*a56);
  a19=(a13*a25);
  a26=(a26-a19);
  a19=(a16*a38);
  a26=(a26+a19);
  a17=(a17/a21);
  a19=(a18*a17);
  a26=(a26-a19);
  a19=(a3*a46);
  a26=(a26-a19);
  a41=(a41*a11);
  a43=(a43*a36);
  a41=(a41-a43);
  a50=(a50*a45);
  a41=(a41+a50);
  a50=(a3*a41);
  a45=(a8*a50);
  a26=(a26+a45);
  a45=(a16*a49);
  a43=(a20*a45);
  a26=(a26+a43);
  a43=(a13*a49);
  a36=(a18*a43);
  a26=(a26-a36);
  if (res[0]!=0) res[0][1]=a26;
  a26=(a13*a35);
  a36=(a0*a56);
  a26=(a26-a36);
  a36=(a14*a17);
  a26=(a26+a36);
  a36=(a16*a40);
  a26=(a26-a36);
  a36=(a3*a51);
  a26=(a26+a36);
  a36=(a6*a50);
  a26=(a26-a36);
  a36=(a0*a45);
  a26=(a26-a36);
  a36=(a14*a43);
  a26=(a26+a36);
  if (res[0]!=0) res[0][2]=a26;
  a26=(a23*a35);
  a36=(a4*a25);
  a26=(a26-a36);
  a36=(a6*a42);
  a11=(a6*a36);
  a26=(a26+a11);
  a1=(a1/a21);
  a11=(a14*a1);
  a26=(a26+a11);
  a11=(a6*a48);
  a19=(a8*a11);
  a26=(a26-a19);
  a27=(a27/a21);
  a19=(a18*a27);
  a26=(a26-a19);
  a22=(a22*a49);
  a26=(a26-a22);
  if (res[0]!=0) res[0][3]=a26;
  a25=(a10*a25);
  a26=(a23*a56);
  a25=(a25-a26);
  a26=(a3*a36);
  a25=(a25-a26);
  a26=(a16*a1);
  a25=(a25-a26);
  a26=(a6*a41);
  a22=(a8*a26);
  a25=(a25+a22);
  a22=(a23*a45);
  a25=(a25-a22);
  a22=(a10*a49);
  a19=(a18*a22);
  a25=(a25+a19);
  a32=(a32/a21);
  a21=(a18*a32);
  a25=(a25+a21);
  if (res[0]!=0) res[0][4]=a25;
  a56=(a4*a56);
  a35=(a10*a35);
  a56=(a56-a35);
  a35=(a3*a11);
  a56=(a56+a35);
  a35=(a16*a27);
  a56=(a56+a35);
  a35=(a6*a26);
  a56=(a56-a35);
  a45=(a4*a45);
  a56=(a56+a45);
  a45=(a14*a22);
  a56=(a56-a45);
  a45=(a14*a32);
  a56=(a56-a45);
  if (res[0]!=0) res[0][5]=a56;
  a56=(a4*a38);
  a45=(a23*a40);
  a56=(a56-a45);
  a45=(a8*a42);
  a35=(a6*a45);
  a56=(a56+a35);
  a35=(a0*a1);
  a56=(a56-a35);
  a35=(a8*a48);
  a25=(a8*a35);
  a56=(a56-a25);
  a25=(a20*a27);
  a56=(a56+a25);
  a24=(a24*a49);
  a56=(a56+a24);
  if (res[0]!=0) res[0][6]=a56;
  a56=(a23*a17);
  a38=(a10*a38);
  a56=(a56-a38);
  a38=(a3*a45);
  a56=(a56-a38);
  a1=(a13*a1);
  a56=(a56+a1);
  a1=(a8*a41);
  a38=(a8*a1);
  a56=(a56+a38);
  a38=(a23*a43);
  a56=(a56+a38);
  a38=(a20*a22);
  a56=(a56-a38);
  a38=(a20*a32);
  a56=(a56-a38);
  if (res[0]!=0) res[0][7]=a56;
  a40=(a10*a40);
  a17=(a4*a17);
  a40=(a40-a17);
  a17=(a3*a35);
  a40=(a40+a17);
  a27=(a13*a27);
  a40=(a40-a27);
  a27=(a6*a1);
  a40=(a40-a27);
  a43=(a4*a43);
  a40=(a40-a43);
  a22=(a0*a22);
  a40=(a40+a22);
  a32=(a0*a32);
  a40=(a40+a32);
  if (res[0]!=0) res[0][8]=a40;
  a40=arg[1]? arg[1][0] : 0;
  a40=(a40-a50);
  if (res[0]!=0) res[0][9]=a40;
  a40=arg[1]? arg[1][1] : 0;
  a40=(a40-a51);
  if (res[0]!=0) res[0][10]=a40;
  a40=arg[1]? arg[1][2] : 0;
  a40=(a40-a46);
  if (res[0]!=0) res[0][11]=a40;
  a40=arg[1]? arg[1][3] : 0;
  a40=(a40-a26);
  if (res[0]!=0) res[0][12]=a40;
  a40=arg[1]? arg[1][4] : 0;
  a40=(a40-a11);
  if (res[0]!=0) res[0][13]=a40;
  a40=arg[1]? arg[1][5] : 0;
  a40=(a40-a36);
  if (res[0]!=0) res[0][14]=a40;
  a40=arg[1]? arg[1][6] : 0;
  a40=(a40-a1);
  if (res[0]!=0) res[0][15]=a40;
  a40=arg[1]? arg[1][7] : 0;
  a40=(a40-a35);
  if (res[0]!=0) res[0][16]=a40;
  a40=arg[1]? arg[1][8] : 0;
  a40=(a40-a45);
  if (res[0]!=0) res[0][17]=a40;
  a40=5.0000000000000000e-01;
  a8=(a40*a8);
  a32=arg[1]? arg[1][21] : 0;
  a22=(a8*a32);
  a6=(a40*a6);
  a43=arg[1]? arg[1][20] : 0;
  a27=(a6*a43);
  a22=(a22+a27);
  a3=(a40*a3);
  a27=arg[1]? arg[1][19] : 0;
  a17=(a3*a27);
  a22=(a22+a17);
  if (res[0]!=0) res[0][18]=a22;
  a22=(a6*a32);
  a17=(a8*a43);
  a22=(a22-a17);
  a17=arg[1]? arg[1][18] : 0;
  a56=(a3*a17);
  a22=(a22-a56);
  if (res[0]!=0) res[0][19]=a22;
  a22=(a8*a27);
  a56=(a3*a32);
  a22=(a22-a56);
  a56=(a6*a17);
  a22=(a22-a56);
  if (res[0]!=0) res[0][20]=a22;
  a3=(a3*a43);
  a6=(a6*a27);
  a3=(a3-a6);
  a8=(a8*a17);
  a3=(a3-a8);
  if (res[0]!=0) res[0][21]=a3;
  a3=(a18*a35);
  a8=(a14*a45);
  a6=(a0*a36);
  a8=(a8+a6);
  a9=(a9*a42);
  a8=(a8+a9);
  a9=(a4*a46);
  a8=(a8+a9);
  a2=(a2*a42);
  a8=(a8+a2);
  a3=(a3-a8);
  a8=(a20*a11);
  a3=(a3+a8);
  a29=(a29*a48);
  a3=(a3-a29);
  a29=(a23*a51);
  a3=(a3+a29);
  a28=(a28*a48);
  a3=(a3-a28);
  a53=(a53*a41);
  a3=(a3-a53);
  a52=(a52*a41);
  a3=(a3-a52);
  a52=arg[0]? arg[0][20] : 0;
  a53=(a52*a32);
  a53=(a40*a53);
  a3=(a3-a53);
  a53=arg[0]? arg[0][21] : 0;
  a28=(a53*a43);
  a28=(a40*a28);
  a3=(a3+a28);
  a28=arg[0]? arg[0][18] : 0;
  a29=(a28*a27);
  a29=(a40*a29);
  a3=(a3+a29);
  a29=arg[0]? arg[0][19] : 0;
  a8=(a29*a17);
  a8=(a40*a8);
  a3=(a3-a8);
  if (res[0]!=0) res[0][22]=a3;
  a45=(a16*a45);
  a12=(a12*a42);
  a45=(a45-a12);
  a36=(a13*a36);
  a45=(a45+a36);
  a46=(a10*a46);
  a45=(a45+a46);
  a5=(a5*a42);
  a45=(a45-a5);
  a33=(a33*a48);
  a45=(a45-a33);
  a30=(a30*a48);
  a45=(a45-a30);
  a18=(a18*a1);
  a45=(a45-a18);
  a57=(a57*a41);
  a45=(a45-a57);
  a20=(a20*a26);
  a45=(a45-a20);
  a23=(a23*a50);
  a45=(a45-a23);
  a54=(a54*a41);
  a45=(a45-a54);
  a54=(a29*a32);
  a54=(a40*a54);
  a45=(a45+a54);
  a54=(a28*a43);
  a54=(a40*a54);
  a45=(a45+a54);
  a54=(a53*a27);
  a54=(a40*a54);
  a45=(a45-a54);
  a54=(a52*a17);
  a54=(a40*a54);
  a45=(a45-a54);
  if (res[0]!=0) res[0][23]=a45;
  a14=(a14*a1);
  a15=(a15*a42);
  a7=(a7*a42);
  a15=(a15+a7);
  a34=(a34*a48);
  a15=(a15+a34);
  a16=(a16*a35);
  a15=(a15+a16);
  a13=(a13*a11);
  a15=(a15+a13);
  a10=(a10*a51);
  a15=(a15+a10);
  a31=(a31*a48);
  a15=(a15+a31);
  a58=(a58*a41);
  a15=(a15+a58);
  a14=(a14-a15);
  a0=(a0*a26);
  a14=(a14+a0);
  a4=(a4*a50);
  a14=(a14+a4);
  a55=(a55*a41);
  a14=(a14-a55);
  a28=(a28*a32);
  a28=(a40*a28);
  a14=(a14+a28);
  a29=(a29*a43);
  a29=(a40*a29);
  a14=(a14-a29);
  a52=(a52*a27);
  a52=(a40*a52);
  a14=(a14+a52);
  a53=(a53*a17);
  a40=(a40*a53);
  a14=(a14-a40);
  if (res[0]!=0) res[0][24]=a14;
  if (res[0]!=0) res[0][25]=a41;
  if (res[0]!=0) res[0][26]=a48;
  if (res[0]!=0) res[0][27]=a42;
  return 0;
}

CASADI_SYMBOL_EXPORT int rotational_ode_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rotational_ode_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rotational_ode_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rotational_ode_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rotational_ode_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rotational_ode_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rotational_ode_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void rotational_ode_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rotational_ode_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int rotational_ode_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rotational_ode_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rotational_ode_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rotational_ode_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rotational_ode_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rotational_ode_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rotational_ode_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rotational_ode_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
